name: Deploy my Lambda 
on: 
  push:
    brnaches: 
      - main
  
jobs: 
  build:
    runs-on: ubuntu-latest
      steps: 
        - name: Check out the code
          uses: actions/checkout@v2
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
        - name: Install Libs
          run: |
              cd function
              python -m pip install --upgrade pip 
              if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
        - name: create zip bundle 
          run: |
              cd function
              zip -r ../${{ github.sha }}.zip .
        - name: Archive Artifact 
          uses: actions/upload-artifact@v2
          with:
            name: ziped-bundle
            path: ${{ github.sha }}.zip
          
